### ISSUE TITLE
facing few minor issues, help will be appreciated 

### ISSUE THREAD

**Issue by moneef** [php-cuong/magento2-faqs-extensions#17]
Hey @Tjitse-E, @php-cuong 

i'm facing few issues with the module i hope you could help me as i'm currently broke and the author asks for fee on requests and sure ill pay ether of you when i get funds.

2- second issue with non-Latin letters, when i input Arabic letters for category name its URL doesn't work anymore it gives me **404 not found**.

## this one have been fixed, it was an entry in url_rewrite table in the database that caused the problem
/*
*> 1- first issue is with `.html` appending how can i remove it or add an option on adminhtml to chose to *append it or not.  i have changed `const FAQ_DOT_HTML = '.html';`  to `const FAQ_DOT_HTML = '';` but 
*still gives me **404 not found** when i remove .html from the url.
*/

**Comment by Tjitse-E** [comment]
@moneef I was facing the first issue myself.  Modifying ` FAQ_DOT_HTML` doesn't work for existing entries because the URL rewrite is already made. You can modify it in the database to solve it for existing entries (table `url_rewrite`).
![sequelpro](https://user-images.githubusercontent.com/14849044/31997122-21a1f834-b98b-11e7-9112-21c7f67b74c0.png)

**Comment by moneef** [comment]
@Tjitse-E  yes i saw that and fixed it.

any idea about the second issue ?

**Comment by php-cuong** [comment]
@moneef You can use this extension for fixing, if it doesn't work in Arabic letters, you can use the codes in this extension for customizing in the Arabic letters.

https://github.com/php-cuong/magento2-vietnamese-url-key
